name: Deploy

on: push

jobs:
  fisrt_job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Variable
        run: echo "${{ secrets.TOKEN_SECRET }}"

      # Configuracion de la app
      - name: setup
        # Se utiliza un action para la instalacion de node o php, o lo que se utilice
        uses: actions/setup-node@v4
        with:
          node-version: '18'
